(cl:in-package robospect_msgs-msg)
(cl:export '(MISSION_STATE-VAL
          MISSION_STATE
          MAX_DISTANCE-VAL
          MAX_DISTANCE
          TRAVELED_DISTANCE-VAL
          TRAVELED_DISTANCE
          STEP_METERS-VAL
          STEP_METERS
          MINIMUM_CRACK_LENGTH-VAL
          MINIMUM_CRACK_LENGTH
          MAX_CRACKS-VAL
          MAX_CRACKS
          MISSION_COMMAND-VAL
          MISSION_COMMAND
          POINTS-VAL
          POINTS
          CURRENT_POINT-VAL
          CURRENT_POINT
          VEHICLE_STATE-VAL
          VEHICLE_STATE
          TIP_X-VAL
          TIP_X
          TIP_Y-VAL
          TIP_Y
          TIP_Z-VAL
          TIP_Z
          TIP_Q1-VAL
          TIP_Q1
          TIP_Q2-VAL
          TIP_Q2
          TIP_Q3-VAL
          TIP_Q3
          TIP_Q4-VAL
          TIP_Q4
          ARM_JOINTS-VAL
          ARM_JOINTS
          ARM_STATE-VAL
          ARM_STATE
          CAMERA_STATE-VAL
          CAMERA_STATE
          IMAGE_FILE_NAME1-VAL
          IMAGE_FILE_NAME1
          IMAGE_FILE_NAME2-VAL
          IMAGE_FILE_NAME2
          PROFILE_FILE_NAME-VAL
          PROFILE_FILE_NAME
          STEREO_FILE_NAME1-VAL
          STEREO_FILE_NAME1
          STEREO_FILE_NAME2-VAL
          STEREO_FILE_NAME2
          CRACK_PIXEL_X-VAL
          CRACK_PIXEL_X
          CRACK_PIXEL_Y-VAL
          CRACK_PIXEL_Y
          CRACK_POSITION_X-VAL
          CRACK_POSITION_X
          CRACK_POSITION_Y-VAL
          CRACK_POSITION_Y
          CRACK_POSITION_Z-VAL
          CRACK_POSITION_Z
          CRACK_ORIENTATION_A-VAL
          CRACK_ORIENTATION_A
          CRACK_ORIENTATION_B-VAL
          CRACK_ORIENTATION_B
          CRACK_ORIENTATION_C-VAL
          CRACK_ORIENTATION_C
          ULTRASONIC_STATE-VAL
          ULTRASONIC_STATE
          CRACK_WIDTH-VAL
          CRACK_WIDTH
          CRACK_DEPTH-VAL
          CRACK_DEPTH
))