(cl:in-package robospect_msgs-msg)
(cl:export '(PLATFORM_MODE-VAL
          PLATFORM_MODE
          DEADMAN_ACTIVE-VAL
          DEADMAN_ACTIVE
          VEHICLE_SPEED_LEVEL-VAL
          VEHICLE_SPEED_LEVEL
          DESIRED_ANGULAR_POSITION-VAL
          DESIRED_ANGULAR_POSITION
          DESIRED_LINEAR_SPEED-VAL
          DESIRED_LINEAR_SPEED
          ARM_DEADMAN_ACTIVE-VAL
          ARM_DEADMAN_ACTIVE
          CURRENT_JOINT-VAL
          CURRENT_JOINT
          ARM_SPEED_LEVEL-VAL
          ARM_SPEED_LEVEL
          CURRENT_JOINT_SPEED-VAL
          CURRENT_JOINT_SPEED
))