(cl:in-package robospect_msgs-msg)
(cl:export '(VEHICLE_X-VAL
          VEHICLE_X
          VEHICLE_Y-VAL
          VEHICLE_Y
          VEHICLE_THETA-VAL
          VEHICLE_THETA
          VEHICLE_LINEAR_SPEED-VAL
          VEHICLE_LINEAR_SPEED
          VEHICLE_ANGULAR_SPEED-VAL
          VEHICLE_ANGULAR_SPEED
          CRANE_X-VAL
          CRANE_X
          CRANE_Y-VAL
          CRANE_Y
          CRANE_Z-VAL
          CRANE_Z
          CRANE_Q1-VAL
          CRANE_Q1
          CRANE_Q2-VAL
          CRANE_Q2
          CRANE_Q3-VAL
          CRANE_Q3
          CRANE_Q4-VAL
          CRANE_Q4
          CRANE_JOINTS-VAL
          CRANE_JOINTS
          PAN_ANGLE-VAL
          PAN_ANGLE
          TILT_ANGLE-VAL
          TILT_ANGLE
          BATTERY_LEVEL-VAL
          BATTERY_LEVEL
          STATE-VAL
          STATE
          COMMAND-VAL
          COMMAND
))