// Generated by gencpp from file robospect_msgs/DetectCrack.msg
// DO NOT EDIT!


#ifndef ROBOSPECT_MSGS_MESSAGE_DETECTCRACK_H
#define ROBOSPECT_MSGS_MESSAGE_DETECTCRACK_H

#include <ros/service_traits.h>


#include <robospect_msgs/DetectCrackRequest.h>
#include <robospect_msgs/DetectCrackResponse.h>


namespace robospect_msgs
{

struct DetectCrack
{

typedef DetectCrackRequest Request;
typedef DetectCrackResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectCrack
} // namespace robospect_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robospect_msgs::DetectCrack > {
  static const char* value()
  {
    return "7ea5332236a44eb592bfa194cbab38e8";
  }

  static const char* value(const ::robospect_msgs::DetectCrack&) { return value(); }
};

template<>
struct DataType< ::robospect_msgs::DetectCrack > {
  static const char* value()
  {
    return "robospect_msgs/DetectCrack";
  }

  static const char* value(const ::robospect_msgs::DetectCrack&) { return value(); }
};


// service_traits::MD5Sum< ::robospect_msgs::DetectCrackRequest> should match 
// service_traits::MD5Sum< ::robospect_msgs::DetectCrack > 
template<>
struct MD5Sum< ::robospect_msgs::DetectCrackRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robospect_msgs::DetectCrack >::value();
  }
  static const char* value(const ::robospect_msgs::DetectCrackRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robospect_msgs::DetectCrackRequest> should match 
// service_traits::DataType< ::robospect_msgs::DetectCrack > 
template<>
struct DataType< ::robospect_msgs::DetectCrackRequest>
{
  static const char* value()
  {
    return DataType< ::robospect_msgs::DetectCrack >::value();
  }
  static const char* value(const ::robospect_msgs::DetectCrackRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robospect_msgs::DetectCrackResponse> should match 
// service_traits::MD5Sum< ::robospect_msgs::DetectCrack > 
template<>
struct MD5Sum< ::robospect_msgs::DetectCrackResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robospect_msgs::DetectCrack >::value();
  }
  static const char* value(const ::robospect_msgs::DetectCrackResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robospect_msgs::DetectCrackResponse> should match 
// service_traits::DataType< ::robospect_msgs::DetectCrack > 
template<>
struct DataType< ::robospect_msgs::DetectCrackResponse>
{
  static const char* value()
  {
    return DataType< ::robospect_msgs::DetectCrack >::value();
  }
  static const char* value(const ::robospect_msgs::DetectCrackResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOSPECT_MSGS_MESSAGE_DETECTCRACK_H
