// Generated by gencpp from file robospect_msgs/GetStereo.msg
// DO NOT EDIT!


#ifndef ROBOSPECT_MSGS_MESSAGE_GETSTEREO_H
#define ROBOSPECT_MSGS_MESSAGE_GETSTEREO_H

#include <ros/service_traits.h>


#include <robospect_msgs/GetStereoRequest.h>
#include <robospect_msgs/GetStereoResponse.h>


namespace robospect_msgs
{

struct GetStereo
{

typedef GetStereoRequest Request;
typedef GetStereoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStereo
} // namespace robospect_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robospect_msgs::GetStereo > {
  static const char* value()
  {
    return "7ea5332236a44eb592bfa194cbab38e8";
  }

  static const char* value(const ::robospect_msgs::GetStereo&) { return value(); }
};

template<>
struct DataType< ::robospect_msgs::GetStereo > {
  static const char* value()
  {
    return "robospect_msgs/GetStereo";
  }

  static const char* value(const ::robospect_msgs::GetStereo&) { return value(); }
};


// service_traits::MD5Sum< ::robospect_msgs::GetStereoRequest> should match 
// service_traits::MD5Sum< ::robospect_msgs::GetStereo > 
template<>
struct MD5Sum< ::robospect_msgs::GetStereoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robospect_msgs::GetStereo >::value();
  }
  static const char* value(const ::robospect_msgs::GetStereoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robospect_msgs::GetStereoRequest> should match 
// service_traits::DataType< ::robospect_msgs::GetStereo > 
template<>
struct DataType< ::robospect_msgs::GetStereoRequest>
{
  static const char* value()
  {
    return DataType< ::robospect_msgs::GetStereo >::value();
  }
  static const char* value(const ::robospect_msgs::GetStereoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robospect_msgs::GetStereoResponse> should match 
// service_traits::MD5Sum< ::robospect_msgs::GetStereo > 
template<>
struct MD5Sum< ::robospect_msgs::GetStereoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robospect_msgs::GetStereo >::value();
  }
  static const char* value(const ::robospect_msgs::GetStereoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robospect_msgs::GetStereoResponse> should match 
// service_traits::DataType< ::robospect_msgs::GetStereo > 
template<>
struct DataType< ::robospect_msgs::GetStereoResponse>
{
  static const char* value()
  {
    return DataType< ::robospect_msgs::GetStereo >::value();
  }
  static const char* value(const ::robospect_msgs::GetStereoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOSPECT_MSGS_MESSAGE_GETSTEREO_H
