// Generated by gencpp from file robospect_msgs/MissionPoint.msg
// DO NOT EDIT!


#ifndef ROBOSPECT_MSGS_MESSAGE_MISSIONPOINT_H
#define ROBOSPECT_MSGS_MESSAGE_MISSIONPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace robospect_msgs
{
template <class ContainerAllocator>
struct MissionPoint_
{
  typedef MissionPoint_<ContainerAllocator> Type;

  MissionPoint_()
    : point()
    , do_crack_detection(false)
    , do_3D_scan(false)
    , do_stereo_image(false)
    , do_ultrasonic_measurements(false)
    , do_teleop_us(false)  {
    }
  MissionPoint_(const ContainerAllocator& _alloc)
    : point(_alloc)
    , do_crack_detection(false)
    , do_3D_scan(false)
    , do_stereo_image(false)
    , do_ultrasonic_measurements(false)
    , do_teleop_us(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef uint8_t _do_crack_detection_type;
  _do_crack_detection_type do_crack_detection;

   typedef uint8_t _do_3D_scan_type;
  _do_3D_scan_type do_3D_scan;

   typedef uint8_t _do_stereo_image_type;
  _do_stereo_image_type do_stereo_image;

   typedef uint8_t _do_ultrasonic_measurements_type;
  _do_ultrasonic_measurements_type do_ultrasonic_measurements;

   typedef uint8_t _do_teleop_us_type;
  _do_teleop_us_type do_teleop_us;





  typedef boost::shared_ptr< ::robospect_msgs::MissionPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robospect_msgs::MissionPoint_<ContainerAllocator> const> ConstPtr;

}; // struct MissionPoint_

typedef ::robospect_msgs::MissionPoint_<std::allocator<void> > MissionPoint;

typedef boost::shared_ptr< ::robospect_msgs::MissionPoint > MissionPointPtr;
typedef boost::shared_ptr< ::robospect_msgs::MissionPoint const> MissionPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robospect_msgs::MissionPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robospect_msgs::MissionPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robospect_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robospect_msgs': ['/home/jaydeep/catkin_ws/src/robospect_common-master/robospect_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::MissionPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::MissionPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::MissionPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::MissionPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::MissionPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::MissionPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robospect_msgs::MissionPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e09177a0ebb8aa226b0293db5898c1dc";
  }

  static const char* value(const ::robospect_msgs::MissionPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe09177a0ebb8aa22ULL;
  static const uint64_t static_value2 = 0x6b0293db5898c1dcULL;
};

template<class ContainerAllocator>
struct DataType< ::robospect_msgs::MissionPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robospect_msgs/MissionPoint";
  }

  static const char* value(const ::robospect_msgs::MissionPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robospect_msgs::MissionPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Mission Point (from GCS to IGC)\n\
\n\
# Tunnel point\n\
geometry_msgs/Point point\n\
\n\
#Inspection parameters\n\
bool do_crack_detection\n\
bool do_3D_scan\n\
bool do_stereo_image\n\
bool do_ultrasonic_measurements\n\
bool do_teleop_us\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::robospect_msgs::MissionPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robospect_msgs::MissionPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
      stream.next(m.do_crack_detection);
      stream.next(m.do_3D_scan);
      stream.next(m.do_stereo_image);
      stream.next(m.do_ultrasonic_measurements);
      stream.next(m.do_teleop_us);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robospect_msgs::MissionPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robospect_msgs::MissionPoint_<ContainerAllocator>& v)
  {
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "do_crack_detection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.do_crack_detection);
    s << indent << "do_3D_scan: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.do_3D_scan);
    s << indent << "do_stereo_image: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.do_stereo_image);
    s << indent << "do_ultrasonic_measurements: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.do_ultrasonic_measurements);
    s << indent << "do_teleop_us: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.do_teleop_us);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSPECT_MSGS_MESSAGE_MISSIONPOINT_H
