// Generated by gencpp from file robospect_msgs/MissionCommandSrvRequest.msg
// DO NOT EDIT!


#ifndef ROBOSPECT_MSGS_MESSAGE_MISSIONCOMMANDSRVREQUEST_H
#define ROBOSPECT_MSGS_MESSAGE_MISSIONCOMMANDSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robospect_msgs/MissionCommand.h>

namespace robospect_msgs
{
template <class ContainerAllocator>
struct MissionCommandSrvRequest_
{
  typedef MissionCommandSrvRequest_<ContainerAllocator> Type;

  MissionCommandSrvRequest_()
    : command()  {
    }
  MissionCommandSrvRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robospect_msgs::MissionCommand_<ContainerAllocator>  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MissionCommandSrvRequest_

typedef ::robospect_msgs::MissionCommandSrvRequest_<std::allocator<void> > MissionCommandSrvRequest;

typedef boost::shared_ptr< ::robospect_msgs::MissionCommandSrvRequest > MissionCommandSrvRequestPtr;
typedef boost::shared_ptr< ::robospect_msgs::MissionCommandSrvRequest const> MissionCommandSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robospect_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robospect_msgs': ['/home/jaydeep/catkin_ws/src/robospect_common-master/robospect_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46007f567dea0180aa2a734c8c8ed65d";
  }

  static const char* value(const ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46007f567dea0180ULL;
  static const uint64_t static_value2 = 0xaa2a734c8c8ed65dULL;
};

template<class ContainerAllocator>
struct DataType< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robospect_msgs/MissionCommandSrvRequest";
  }

  static const char* value(const ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MissionCommand command\n\
\n\
================================================================================\n\
MSG: robospect_msgs/MissionCommand\n\
# System mission command (from GCS to IGC)\n\
string command\n\
\n\
# Mission variable\n\
float32 variable\n\
\n\
# Mission Points for missions composed of waypoints\n\
MissionPoint[] points\n\
\n\
================================================================================\n\
MSG: robospect_msgs/MissionPoint\n\
# Mission Point (from GCS to IGC)\n\
\n\
# Tunnel point\n\
geometry_msgs/Point point\n\
\n\
#Inspection parameters\n\
bool do_crack_detection\n\
bool do_3D_scan\n\
bool do_stereo_image\n\
bool do_ultrasonic_measurements\n\
bool do_teleop_us\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionCommandSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robospect_msgs::MissionCommandSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    s << std::endl;
    Printer< ::robospect_msgs::MissionCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSPECT_MSGS_MESSAGE_MISSIONCOMMANDSRVREQUEST_H
