// Generated by gencpp from file robospect_msgs/MissionCommand.msg
// DO NOT EDIT!


#ifndef ROBOSPECT_MSGS_MESSAGE_MISSIONCOMMAND_H
#define ROBOSPECT_MSGS_MESSAGE_MISSIONCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robospect_msgs/MissionPoint.h>

namespace robospect_msgs
{
template <class ContainerAllocator>
struct MissionCommand_
{
  typedef MissionCommand_<ContainerAllocator> Type;

  MissionCommand_()
    : command()
    , variable(0.0)
    , points()  {
    }
  MissionCommand_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , variable(0.0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef float _variable_type;
  _variable_type variable;

   typedef std::vector< ::robospect_msgs::MissionPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robospect_msgs::MissionPoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::robospect_msgs::MissionCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robospect_msgs::MissionCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MissionCommand_

typedef ::robospect_msgs::MissionCommand_<std::allocator<void> > MissionCommand;

typedef boost::shared_ptr< ::robospect_msgs::MissionCommand > MissionCommandPtr;
typedef boost::shared_ptr< ::robospect_msgs::MissionCommand const> MissionCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robospect_msgs::MissionCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robospect_msgs::MissionCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robospect_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robospect_msgs': ['/home/jaydeep/catkin_ws/src/robospect_common-master/robospect_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::MissionCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::MissionCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::MissionCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::MissionCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::MissionCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::MissionCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robospect_msgs::MissionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff86b621d1d6dd071a2101fe0b67f6fa";
  }

  static const char* value(const ::robospect_msgs::MissionCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff86b621d1d6dd07ULL;
  static const uint64_t static_value2 = 0x1a2101fe0b67f6faULL;
};

template<class ContainerAllocator>
struct DataType< ::robospect_msgs::MissionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robospect_msgs/MissionCommand";
  }

  static const char* value(const ::robospect_msgs::MissionCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robospect_msgs::MissionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# System mission command (from GCS to IGC)\n\
string command\n\
\n\
# Mission variable\n\
float32 variable\n\
\n\
# Mission Points for missions composed of waypoints\n\
MissionPoint[] points\n\
\n\
================================================================================\n\
MSG: robospect_msgs/MissionPoint\n\
# Mission Point (from GCS to IGC)\n\
\n\
# Tunnel point\n\
geometry_msgs/Point point\n\
\n\
#Inspection parameters\n\
bool do_crack_detection\n\
bool do_3D_scan\n\
bool do_stereo_image\n\
bool do_ultrasonic_measurements\n\
bool do_teleop_us\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::robospect_msgs::MissionCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robospect_msgs::MissionCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.variable);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robospect_msgs::MissionCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robospect_msgs::MissionCommand_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "variable: ";
    Printer<float>::stream(s, indent + "  ", v.variable);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robospect_msgs::MissionPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSPECT_MSGS_MESSAGE_MISSIONCOMMAND_H
