// Generated by gencpp from file robospect_msgs/PadStatus.msg
// DO NOT EDIT!


#ifndef ROBOSPECT_MSGS_MESSAGE_PADSTATUS_H
#define ROBOSPECT_MSGS_MESSAGE_PADSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robospect_msgs
{
template <class ContainerAllocator>
struct PadStatus_
{
  typedef PadStatus_<ContainerAllocator> Type;

  PadStatus_()
    : platform_mode()
    , deadman_active(false)
    , vehicle_speed_level(0.0)
    , desired_angular_position(0.0)
    , desired_linear_speed(0.0)
    , arm_deadman_active(false)
    , current_joint()
    , arm_speed_level(0.0)
    , current_joint_speed(0.0)  {
    }
  PadStatus_(const ContainerAllocator& _alloc)
    : platform_mode(_alloc)
    , deadman_active(false)
    , vehicle_speed_level(0.0)
    , desired_angular_position(0.0)
    , desired_linear_speed(0.0)
    , arm_deadman_active(false)
    , current_joint(_alloc)
    , arm_speed_level(0.0)
    , current_joint_speed(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _platform_mode_type;
  _platform_mode_type platform_mode;

   typedef uint8_t _deadman_active_type;
  _deadman_active_type deadman_active;

   typedef float _vehicle_speed_level_type;
  _vehicle_speed_level_type vehicle_speed_level;

   typedef float _desired_angular_position_type;
  _desired_angular_position_type desired_angular_position;

   typedef float _desired_linear_speed_type;
  _desired_linear_speed_type desired_linear_speed;

   typedef uint8_t _arm_deadman_active_type;
  _arm_deadman_active_type arm_deadman_active;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _current_joint_type;
  _current_joint_type current_joint;

   typedef float _arm_speed_level_type;
  _arm_speed_level_type arm_speed_level;

   typedef float _current_joint_speed_type;
  _current_joint_speed_type current_joint_speed;





  typedef boost::shared_ptr< ::robospect_msgs::PadStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robospect_msgs::PadStatus_<ContainerAllocator> const> ConstPtr;

}; // struct PadStatus_

typedef ::robospect_msgs::PadStatus_<std::allocator<void> > PadStatus;

typedef boost::shared_ptr< ::robospect_msgs::PadStatus > PadStatusPtr;
typedef boost::shared_ptr< ::robospect_msgs::PadStatus const> PadStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robospect_msgs::PadStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robospect_msgs::PadStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robospect_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robospect_msgs': ['/home/jaydeep/catkin_ws/src/robospect_common/robospect_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::PadStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::PadStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::PadStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::PadStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::PadStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::PadStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robospect_msgs::PadStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84734e1416ed6ff9c1d61313de9e8074";
  }

  static const char* value(const ::robospect_msgs::PadStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84734e1416ed6ff9ULL;
  static const uint64_t static_value2 = 0xc1d61313de9e8074ULL;
};

template<class ContainerAllocator>
struct DataType< ::robospect_msgs::PadStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robospect_msgs/PadStatus";
  }

  static const char* value(const ::robospect_msgs::PadStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robospect_msgs::PadStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string platform_mode\n\
bool deadman_active\n\
float32 vehicle_speed_level\n\
float32 desired_angular_position\n\
float32 desired_linear_speed\n\
\n\
bool arm_deadman_active\n\
string current_joint\n\
float32 arm_speed_level\n\
float32 current_joint_speed\n\
";
  }

  static const char* value(const ::robospect_msgs::PadStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robospect_msgs::PadStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.platform_mode);
      stream.next(m.deadman_active);
      stream.next(m.vehicle_speed_level);
      stream.next(m.desired_angular_position);
      stream.next(m.desired_linear_speed);
      stream.next(m.arm_deadman_active);
      stream.next(m.current_joint);
      stream.next(m.arm_speed_level);
      stream.next(m.current_joint_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PadStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robospect_msgs::PadStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robospect_msgs::PadStatus_<ContainerAllocator>& v)
  {
    s << indent << "platform_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.platform_mode);
    s << indent << "deadman_active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.deadman_active);
    s << indent << "vehicle_speed_level: ";
    Printer<float>::stream(s, indent + "  ", v.vehicle_speed_level);
    s << indent << "desired_angular_position: ";
    Printer<float>::stream(s, indent + "  ", v.desired_angular_position);
    s << indent << "desired_linear_speed: ";
    Printer<float>::stream(s, indent + "  ", v.desired_linear_speed);
    s << indent << "arm_deadman_active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.arm_deadman_active);
    s << indent << "current_joint: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.current_joint);
    s << indent << "arm_speed_level: ";
    Printer<float>::stream(s, indent + "  ", v.arm_speed_level);
    s << indent << "current_joint_speed: ";
    Printer<float>::stream(s, indent + "  ", v.current_joint_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSPECT_MSGS_MESSAGE_PADSTATUS_H
