// Generated by gencpp from file robospect_msgs/PlatformCommandSrvRequest.msg
// DO NOT EDIT!


#ifndef ROBOSPECT_MSGS_MESSAGE_PLATFORMCOMMANDSRVREQUEST_H
#define ROBOSPECT_MSGS_MESSAGE_PLATFORMCOMMANDSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robospect_msgs/PlatformCommand.h>

namespace robospect_msgs
{
template <class ContainerAllocator>
struct PlatformCommandSrvRequest_
{
  typedef PlatformCommandSrvRequest_<ContainerAllocator> Type;

  PlatformCommandSrvRequest_()
    : command()  {
    }
  PlatformCommandSrvRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robospect_msgs::PlatformCommand_<ContainerAllocator>  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlatformCommandSrvRequest_

typedef ::robospect_msgs::PlatformCommandSrvRequest_<std::allocator<void> > PlatformCommandSrvRequest;

typedef boost::shared_ptr< ::robospect_msgs::PlatformCommandSrvRequest > PlatformCommandSrvRequestPtr;
typedef boost::shared_ptr< ::robospect_msgs::PlatformCommandSrvRequest const> PlatformCommandSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robospect_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robospect_msgs': ['/home/jaydeep/catkin_ws/src/robospect_common/robospect_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "793ae9513e57f4164876252f6b2624cd";
  }

  static const char* value(const ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x793ae9513e57f416ULL;
  static const uint64_t static_value2 = 0x4876252f6b2624cdULL;
};

template<class ContainerAllocator>
struct DataType< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robospect_msgs/PlatformCommandSrvRequest";
  }

  static const char* value(const ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PlatformCommand command\n\
\n\
================================================================================\n\
MSG: robospect_msgs/PlatformCommand\n\
#Command string (from IGC to vehicle)\n\
string command\n\
\n\
#Variables related to the command\n\
float32[] variables\n\
";
  }

  static const char* value(const ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlatformCommandSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robospect_msgs::PlatformCommandSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    s << std::endl;
    Printer< ::robospect_msgs::PlatformCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSPECT_MSGS_MESSAGE_PLATFORMCOMMANDSRVREQUEST_H
