// Generated by gencpp from file robospect_msgs/PlatformCommand.msg
// DO NOT EDIT!


#ifndef ROBOSPECT_MSGS_MESSAGE_PLATFORMCOMMAND_H
#define ROBOSPECT_MSGS_MESSAGE_PLATFORMCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robospect_msgs
{
template <class ContainerAllocator>
struct PlatformCommand_
{
  typedef PlatformCommand_<ContainerAllocator> Type;

  PlatformCommand_()
    : command()
    , variables()  {
    }
  PlatformCommand_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , variables(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _variables_type;
  _variables_type variables;





  typedef boost::shared_ptr< ::robospect_msgs::PlatformCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robospect_msgs::PlatformCommand_<ContainerAllocator> const> ConstPtr;

}; // struct PlatformCommand_

typedef ::robospect_msgs::PlatformCommand_<std::allocator<void> > PlatformCommand;

typedef boost::shared_ptr< ::robospect_msgs::PlatformCommand > PlatformCommandPtr;
typedef boost::shared_ptr< ::robospect_msgs::PlatformCommand const> PlatformCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robospect_msgs::PlatformCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robospect_msgs::PlatformCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robospect_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robospect_msgs': ['/home/jaydeep/catkin_ws/src/robospect_common/robospect_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::PlatformCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::PlatformCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::PlatformCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::PlatformCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::PlatformCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::PlatformCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robospect_msgs::PlatformCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "293224312bb8f98f47447e2fafdcdebf";
  }

  static const char* value(const ::robospect_msgs::PlatformCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x293224312bb8f98fULL;
  static const uint64_t static_value2 = 0x47447e2fafdcdebfULL;
};

template<class ContainerAllocator>
struct DataType< ::robospect_msgs::PlatformCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robospect_msgs/PlatformCommand";
  }

  static const char* value(const ::robospect_msgs::PlatformCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robospect_msgs::PlatformCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Command string (from IGC to vehicle)\n\
string command\n\
\n\
#Variables related to the command\n\
float32[] variables\n\
";
  }

  static const char* value(const ::robospect_msgs::PlatformCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robospect_msgs::PlatformCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.variables);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlatformCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robospect_msgs::PlatformCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robospect_msgs::PlatformCommand_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "variables[]" << std::endl;
    for (size_t i = 0; i < v.variables.size(); ++i)
    {
      s << indent << "  variables[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.variables[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSPECT_MSGS_MESSAGE_PLATFORMCOMMAND_H
