// Generated by gencpp from file robospect_msgs/PlatformResponse.msg
// DO NOT EDIT!


#ifndef ROBOSPECT_MSGS_MESSAGE_PLATFORMRESPONSE_H
#define ROBOSPECT_MSGS_MESSAGE_PLATFORMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robospect_msgs/PlatformCommand.h>

namespace robospect_msgs
{
template <class ContainerAllocator>
struct PlatformResponse_
{
  typedef PlatformResponse_<ContainerAllocator> Type;

  PlatformResponse_()
    : command()
    , result()  {
    }
  PlatformResponse_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robospect_msgs::PlatformCommand_<ContainerAllocator>  _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::robospect_msgs::PlatformResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robospect_msgs::PlatformResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlatformResponse_

typedef ::robospect_msgs::PlatformResponse_<std::allocator<void> > PlatformResponse;

typedef boost::shared_ptr< ::robospect_msgs::PlatformResponse > PlatformResponsePtr;
typedef boost::shared_ptr< ::robospect_msgs::PlatformResponse const> PlatformResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robospect_msgs::PlatformResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robospect_msgs::PlatformResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robospect_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robospect_msgs': ['/home/jaydeep/catkin_ws/src/robospect_common-master/robospect_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::PlatformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robospect_msgs::PlatformResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::PlatformResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robospect_msgs::PlatformResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::PlatformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robospect_msgs::PlatformResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robospect_msgs::PlatformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cdb3d8ea82bc20c32222eefe99076a1b";
  }

  static const char* value(const ::robospect_msgs::PlatformResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcdb3d8ea82bc20c3ULL;
  static const uint64_t static_value2 = 0x2222eefe99076a1bULL;
};

template<class ContainerAllocator>
struct DataType< ::robospect_msgs::PlatformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robospect_msgs/PlatformResponse";
  }

  static const char* value(const ::robospect_msgs::PlatformResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robospect_msgs::PlatformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Command being executed\n\
PlatformCommand command\n\
\n\
# Result of the command\n\
string result\n\
\n\
================================================================================\n\
MSG: robospect_msgs/PlatformCommand\n\
#Command string (from IGC to vehicle)\n\
string command\n\
\n\
#Variables related to the command\n\
float32[] variables\n\
";
  }

  static const char* value(const ::robospect_msgs::PlatformResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robospect_msgs::PlatformResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlatformResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robospect_msgs::PlatformResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robospect_msgs::PlatformResponse_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    s << std::endl;
    Printer< ::robospect_msgs::PlatformCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSPECT_MSGS_MESSAGE_PLATFORMRESPONSE_H
