// Generated by gencpp from file robospect_msgs/ScanProfile.msg
// DO NOT EDIT!


#ifndef ROBOSPECT_MSGS_MESSAGE_SCANPROFILE_H
#define ROBOSPECT_MSGS_MESSAGE_SCANPROFILE_H

#include <ros/service_traits.h>


#include <robospect_msgs/ScanProfileRequest.h>
#include <robospect_msgs/ScanProfileResponse.h>


namespace robospect_msgs
{

struct ScanProfile
{

typedef ScanProfileRequest Request;
typedef ScanProfileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ScanProfile
} // namespace robospect_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robospect_msgs::ScanProfile > {
  static const char* value()
  {
    return "e2cc9e9d8c464550830df49c160979ad";
  }

  static const char* value(const ::robospect_msgs::ScanProfile&) { return value(); }
};

template<>
struct DataType< ::robospect_msgs::ScanProfile > {
  static const char* value()
  {
    return "robospect_msgs/ScanProfile";
  }

  static const char* value(const ::robospect_msgs::ScanProfile&) { return value(); }
};


// service_traits::MD5Sum< ::robospect_msgs::ScanProfileRequest> should match 
// service_traits::MD5Sum< ::robospect_msgs::ScanProfile > 
template<>
struct MD5Sum< ::robospect_msgs::ScanProfileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robospect_msgs::ScanProfile >::value();
  }
  static const char* value(const ::robospect_msgs::ScanProfileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robospect_msgs::ScanProfileRequest> should match 
// service_traits::DataType< ::robospect_msgs::ScanProfile > 
template<>
struct DataType< ::robospect_msgs::ScanProfileRequest>
{
  static const char* value()
  {
    return DataType< ::robospect_msgs::ScanProfile >::value();
  }
  static const char* value(const ::robospect_msgs::ScanProfileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robospect_msgs::ScanProfileResponse> should match 
// service_traits::MD5Sum< ::robospect_msgs::ScanProfile > 
template<>
struct MD5Sum< ::robospect_msgs::ScanProfileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robospect_msgs::ScanProfile >::value();
  }
  static const char* value(const ::robospect_msgs::ScanProfileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robospect_msgs::ScanProfileResponse> should match 
// service_traits::DataType< ::robospect_msgs::ScanProfile > 
template<>
struct DataType< ::robospect_msgs::ScanProfileResponse>
{
  static const char* value()
  {
    return DataType< ::robospect_msgs::ScanProfile >::value();
  }
  static const char* value(const ::robospect_msgs::ScanProfileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOSPECT_MSGS_MESSAGE_SCANPROFILE_H
