// Generated by gencpp from file robospect_msgs/SetControlMode.msg
// DO NOT EDIT!


#ifndef ROBOSPECT_MSGS_MESSAGE_SETCONTROLMODE_H
#define ROBOSPECT_MSGS_MESSAGE_SETCONTROLMODE_H

#include <ros/service_traits.h>


#include <robospect_msgs/SetControlModeRequest.h>
#include <robospect_msgs/SetControlModeResponse.h>


namespace robospect_msgs
{

struct SetControlMode
{

typedef SetControlModeRequest Request;
typedef SetControlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetControlMode
} // namespace robospect_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robospect_msgs::SetControlMode > {
  static const char* value()
  {
    return "b696448a6984c2e37a93990a5f048086";
  }

  static const char* value(const ::robospect_msgs::SetControlMode&) { return value(); }
};

template<>
struct DataType< ::robospect_msgs::SetControlMode > {
  static const char* value()
  {
    return "robospect_msgs/SetControlMode";
  }

  static const char* value(const ::robospect_msgs::SetControlMode&) { return value(); }
};


// service_traits::MD5Sum< ::robospect_msgs::SetControlModeRequest> should match 
// service_traits::MD5Sum< ::robospect_msgs::SetControlMode > 
template<>
struct MD5Sum< ::robospect_msgs::SetControlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robospect_msgs::SetControlMode >::value();
  }
  static const char* value(const ::robospect_msgs::SetControlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robospect_msgs::SetControlModeRequest> should match 
// service_traits::DataType< ::robospect_msgs::SetControlMode > 
template<>
struct DataType< ::robospect_msgs::SetControlModeRequest>
{
  static const char* value()
  {
    return DataType< ::robospect_msgs::SetControlMode >::value();
  }
  static const char* value(const ::robospect_msgs::SetControlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robospect_msgs::SetControlModeResponse> should match 
// service_traits::MD5Sum< ::robospect_msgs::SetControlMode > 
template<>
struct MD5Sum< ::robospect_msgs::SetControlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robospect_msgs::SetControlMode >::value();
  }
  static const char* value(const ::robospect_msgs::SetControlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robospect_msgs::SetControlModeResponse> should match 
// service_traits::DataType< ::robospect_msgs::SetControlMode > 
template<>
struct DataType< ::robospect_msgs::SetControlModeResponse>
{
  static const char* value()
  {
    return DataType< ::robospect_msgs::SetControlMode >::value();
  }
  static const char* value(const ::robospect_msgs::SetControlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOSPECT_MSGS_MESSAGE_SETCONTROLMODE_H
